workflows:
  ios-workflow-ipa:
    name: iOS Workflow IPA
    integrations:
      app_store_connect: AppOxDataCodeMagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: br.com.oxford.oxdata.app
      vars:
        # App Apple ID
        APP_APPLE_ID: 6751540182
      flutter: 3.32.8
    scripts:
      - name: Setup code signing settings on Xcode
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          buildVersionName=$(grep 'version:' pubspec.yaml | sed 's/version: \([0-9.]*\).*/\1/')
          buildNumber=$(($(app-store-connect get-latest-testflight-build-number $APP_APPLE_ID) + 1))
          flutter build ipa --obfuscate --split-debug-info --release \
            --build-name=$buildVersionName \
            --build-number=$buildNumber \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
        expire_build_submitted_for_review: true
        submit_to_app_store: false
      # email:
      #   recipients:
      #     - email@gmail.com
      #   notify:
      #     success: true
      #     failure: true
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
      cancel_previous_builds: true